### ISSUE TITLE
Timing problem with SSR demo example ?

### ISSUE THREAD

**Issue by marcelh89** [sinnerschrader/feature-hub#706]
I'm having some (maybe timing) issue with the SSR demo passing state from server to client.

- I'm running the "server-side-rendering" demo.

- Added a feature-service like described here **https://feature-hub.io/docs/guides/server-side-rendering** in first chapter State Serialization "As a Consumer"
- added service definitions in client integrator and server integrator and feature app

The applications seems to start correctly but in browser log I get an error during initialization of the feature service (on client side) where serializedStateManager.getSerializedState() is not defined and so is "count"

``` 
export const countServiceDefinition = {
  id: 'acme:count-service',

  dependencies: {
    featureServices: {
      's2:serialized-state-manager': '^1.0.0',
    },
  },

  create(env) {
    let count = 0;

    const serializedStateManager =
      env.featureServices['s2:serialized-state-manager'];

    if (typeof window === 'undefined') {
      // on the server
      serializedStateManager.register(() => JSON.stringify({count}));
    } else {
      // on the client
      count = JSON.parse(serializedStateManager.getSerializedState()).count;
    }

    return {
      '1.0.0': () => ({
        featureService: {
          // We assume the setCount method is called by consumers while they are
          // rendered on the server.
          setCount(newCount) {
            count = newCount;
          },

          getCount() {
            return count;
          },
        },
      }),
    };
  },
};
```

```
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.create (count-service.ts:21:20)
    at FeatureServiceRegistry.registerFeatureService (feature-service-registry.js:153:1)
    at FeatureServiceRegistry.registerFeatureServices (feature-service-registry.js:86:1)
    at Object.createFeatureHub (create-feature-hub.js:30:1)
    at integrator.tsx:38:48
    at Object../src/server-side-rendering/integrator.tsx (integrator.tsx:79:3)
    at __webpack_require__ (bootstrap:18:1)
    at startup:4:1
    at startup:4:1
```

**Comment by unstubbable** [comment]
I understand you are are doing this by extending the SSR demo with the above mentioned Feature Service? If yes, can you please push this to a fork, so we can have a look?

**Comment by marcelh89** [comment]
Here's the fork https://github.com/marcelh89/feature-hub
Committed to branch "ssr-demo-with-featureservice"

**Comment by unstubbable** [comment]
This is indeed a timing/order problem. If the count feature service reads from the serialized state manager within its `create` function, it needs to be registered after the integrator has called `setSerializedStates`. See https://github.com/sinnerschrader/feature-hub/commit/35b37d49260857e1ead4111e252eda20d6d2e31d on how to do this.

Admittedly this is not optimal. We will think about adding a definition factory function to the serialized state manager that would allow to register all feature services at the same time.
